imu:
  sub_topic: imu_synced
  sub_buf_size: 100000
odom:
  sub_topic: odom_synced
  sub_buf_size: 100000
  pub_topic: front_odom
  pub_buf_size: 100
  frame_id: odom
  child_frame_id: base_footprint
laser:
  sub_topic: scan_undistorted
  sub_buf_size: 100000

front_end:
  scan_match_name: pcl_icp
  pcl_icp:
    max_iteration: 100
    resolution: 1
    scan2map: false
    MaxCorrespondenceDistance: 1
    EuclideanFitnessEpsilon: 0.001
    TransformationEpsilon: 1e-10
  pcl_ndt:
    MaximumIterations: 40
    GridCentre: [0.0,0.0]
    GridExtent: [20,20]
    GridStep: [20,20]
    OptimizationStepSize: [0.4,0.4,0.1]
    TransformationEpsilon: 1e-9
    resolution: 1
    scan2map: false

